app_settings:
  page_title: AIBTCdev Crews
  layout: wide

file_settings:
  agents_file: aibtcdev_agents.py
  app_file: aibtcdev_app.py
  crews_file: aibtcdev_crews.py
  config_file: aibtcdev_config.yaml
  tasks_file: aibtcdev_tasks.py
  tools_file: aibtcdev_tools.py
  utils_file: aibtcdev_utils.py

model_settings:
  OpenAI:
    OPENAI_MODEL_NAME: gpt-4o
    OPENAI_API_BASE: https://api.openai.com/v1
  ClaudeOpus:
    OPENAI_MODEL_NAME: claude-3-opus-20240229
    OPENAI_API_BASE: https://api.anthropic.com/v1
  ClaudeSonnet:
    OPENAI_MODEL_NAME: claude-3-5-sonnet-20240620
    OPENAI_API_BASE: https://api.anthropic.com/v1
