app_settings:
  page_title: "AIBTCdev Interactive Wallet Manager"
  layout: "wide"

model_settings:
  OpenAI:
    OPENAI_API_BASE: "https://api.openai.com/v1"
    OPENAI_MODEL_NAME: "gpt-3.5-turbo"

agents:
  # This section was likely populated dynamically based on the agents.py file
  # Example structure:
  # AgentClassName:
  #   MethodName: method_function_name

crews:
  # This section was likely populated dynamically based on the crews.py file
  # Example structure:
  # CrewName:
  #   MethodName: method_function_name

tasks:
  # This section was likely populated dynamically based on the tasks.py file
  # Example structure:
  # TaskName:
  #   MethodName: method_function_name

tools:
  # This section was likely populated dynamically based on the tools.py file
  # Example structure:
  # ToolClassName:
  #   MethodName: method_function_name